name: Rust

on:
  push:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: build
      run: docker run --rm -v "$(pwd)":/src ghcr.io/recmo/rust-static-build:1.63-x86_64 cargo build --release
    - name: install
      run: cargo install --release
    - name: upload
      uses: actions/upload-artifact@v3
      with:
          name: pong
          path: ./target/x86*/release/pong
